export const promptTargets = ['studio', 'suno', 'udio']

export const descriptors = [
  {
    id: 'bright',
    category: 'Timbre',
    label: 'Bright',
    definition: 'Forward upper partial presence that reads as shiny, clear, or lifted.',
    usage_note: 'Useful when you need pop clarity or a vocal that cuts through dense production.',
    caution: 'Too much brightness can turn brittle or childish.',
    artist_refs_primary: ['Carly Rae Jepsen', 'Ariana Grande'],
    artist_refs_secondary: ['Troye Sivan', 'Robyn'],
  },
  {
    id: 'dark',
    category: 'Timbre',
    label: 'Dark',
    definition: 'Reduced brightness with a shaded tone center and more low-mid emphasis.',
    usage_note: 'Useful for sensual, mature, nocturnal, or grounded identities.',
    caution: 'Can become muddy if paired with weak articulation.',
    artist_refs_primary: ['Sade', 'Lana Del Rey'],
    artist_refs_secondary: ['The National', 'Lorde'],
  },
  {
    id: 'airy',
    category: 'Texture',
    label: 'Airy',
    definition: 'Audible breath leakage around the tone for softness and intimacy.',
    usage_note: 'Works well for close-mic verses and low-pressure phrasing.',
    caution: 'Can erase pitch definition if overused.',
    artist_refs_primary: ['Billie Eilish', 'Clairo'],
    artist_refs_secondary: ['Phoebe Bridgers', 'Cigarettes After Sex'],
  },
  {
    id: 'raspy',
    category: 'Texture',
    label: 'Raspy',
    definition: 'Grain or friction in the tone, ranging from subtle edge to near-breakup.',
    usage_note: 'Adds emotional wear, urgency, and human imperfection.',
    caution: 'Too much can read as strain or generic rock cosplay.',
    artist_refs_primary: ['Miley Cyrus', 'Janis Joplin'],
    artist_refs_secondary: ['Lewis Capaldi', 'P!nk'],
  },
  {
    id: 'tight-phrasing',
    category: 'Phrasing',
    label: 'Tight phrasing',
    definition: 'Rhythmic precision with clipped contour and deliberate timing.',
    usage_note: 'Useful for modern pop, alt-R&B, and rhythm-led lines.',
    caution: 'Can sound mechanical if combined with too little dynamic nuance.',
    artist_refs_primary: ['Dua Lipa', 'Doja Cat'],
    artist_refs_secondary: ['Charli xcx', 'Sabrina Carpenter'],
  },
  {
    id: 'loose-phrasing',
    category: 'Phrasing',
    label: 'Loose phrasing',
    definition: 'Elastic line delivery with slight lateness, conversational drag, or spillover.',
    usage_note: 'Useful when you want humanity, narration, or a lived-in feel.',
    caution: 'Can sound lazy if the groove is not anchored.',
    artist_refs_primary: ['Feist', 'Amy Winehouse'],
    artist_refs_secondary: ['Norah Jones', 'Hozier'],
  },
  {
    id: 'forward-placement',
    category: 'Placement',
    label: 'Forward placement',
    definition: 'Tone feels projected toward the front of the face, with immediate presence.',
    usage_note: 'Good for intelligibility and contemporary proximity.',
    caution: 'Can become nasal or sharp without balance.',
    artist_refs_primary: ['Troye Sivan', 'Taylor Swift'],
    artist_refs_secondary: ['Olivia Rodrigo', 'The Weeknd'],
  },
  {
    id: 'soft-consonants',
    category: 'Articulation',
    label: 'Soft consonants',
    definition: 'Rounded, less percussive diction that keeps the line gentle.',
    usage_note: 'Useful for intimacy and dreamier blends.',
    caution: 'Can smear lyrics into mush.',
    artist_refs_primary: ['Lana Del Rey', 'Cigarettes After Sex'],
    artist_refs_secondary: ['Sade', 'Men I Trust'],
  },
  {
    id: 'sharp-consonants',
    category: 'Articulation',
    label: 'Sharp consonants',
    definition: 'Clear articulated attacks that sharpen text and rhythm.',
    usage_note: 'Useful when the lyric itself needs to carry impact.',
    caution: 'Can feel aggressive or over-enunciated.',
    artist_refs_primary: ['Dua Lipa', 'Emeli Sandé'],
    artist_refs_secondary: ['P!nk', 'Adele'],
  },
  {
    id: 'close-mic',
    category: 'Production feel',
    label: 'Close mic',
    definition: 'Intimate recording perspective with low distance and audible detail.',
    usage_note: 'Best for confessional delivery and breath detail.',
    caution: 'Exposes every flaw and can make bigger emotions feel cramped.',
    artist_refs_primary: ['Billie Eilish', 'Phoebe Bridgers'],
    artist_refs_secondary: ['Clairo', 'Bon Iver'],
  },
]

export const artists = [
  {
    artist_name: 'Billie Eilish',
    summary: 'Controlled intimacy, light weight, close-mic softness, and careful edge without classic diva projection.',
    descriptor_ids: ['airy', 'forward-placement', 'close-mic', 'soft-consonants'],
    prompts: {
      studio: 'light intimate vocal, close-mic, controlled breath, low-pressure phrasing, delicate clarity',
      suno: 'soft intimate close-mic vocal, breathy but controlled, delicate modern pop phrasing',
      udio: 'whisper-close intimate vocal, light breath texture, fragile but precise delivery',
    },
  },
  {
    artist_name: 'Dua Lipa',
    summary: 'Centered pop authority, tight phrasing, clean tone, cool control, and grounded rhythmic confidence.',
    descriptor_ids: ['bright', 'tight-phrasing', 'sharp-consonants'],
    prompts: {
      studio: 'clean modern pop vocal, rhythmic precision, grounded midrange authority, controlled lift',
      suno: 'confident modern pop vocal, clean tone, tight phrasing, rhythmic and polished',
      udio: 'steady polished female pop lead, cool controlled tone, rhythmic articulation',
    },
  },
  {
    artist_name: 'Miley Cyrus',
    summary: 'Forward pop-rock identity with controlled rasp, direct attitude, and emotional abrasion.',
    descriptor_ids: ['raspy', 'sharp-consonants', 'forward-placement'],
    prompts: {
      studio: 'forward pop-rock vocal, controlled rasp, direct phrasing, emotional grit',
      suno: 'raspy modern pop-rock lead, edgy but controlled, expressive and direct',
      udio: 'grainy female rock-pop vocal, forward placement, attitude and grit',
    },
  },
  {
    artist_name: 'Sade',
    summary: 'Dark silk, low-pressure confidence, restrained sensuality, and elegant understatement.',
    descriptor_ids: ['dark', 'soft-consonants', 'loose-phrasing'],
    prompts: {
      studio: 'dark sensual vocal, smooth low-pressure delivery, elegant phrasing, understated presence',
      suno: 'smooth dark intimate vocal, sensual and restrained, elegant phrasing',
      udio: 'dark velvety lead vocal, soft diction, minimal drama, sensual calm',
    },
  },
  {
    artist_name: 'Hozier',
    summary: 'Earthy storytelling, open resonance, loose phrasing, and grounded emotional scale.',
    descriptor_ids: ['dark', 'loose-phrasing', 'sharp-consonants'],
    prompts: {
      studio: 'earthy storyteller vocal, open resonance, grounded phrasing, human and lived-in',
      suno: 'earthy expressive male vocal, storytelling feel, warm resonance, organic delivery',
      udio: 'rich grounded singer-songwriter voice, earthy tone, loose human phrasing',
    },
  },
  {
    artist_name: 'Robyn',
    summary: 'Bright emotional pop with control, tension, and clear synthetic-era identity.',
    descriptor_ids: ['bright', 'tight-phrasing', 'sharp-consonants'],
    prompts: {
      studio: 'bright emotional pop lead, clean tension, precise phrasing, clear top-end energy',
      suno: 'bright modern pop vocal, emotional restraint, precise and tense phrasing',
      udio: 'sharp bright electropop voice, focused and emotional, tightly delivered',
    },
  },
]

export const archetypes = [
  {
    id: 'cinematic-surge',
    label: 'Cinematic Surge',
    definition: 'Large dramatic cinematic rise with blooming emotion, widening scale, and pressured lift.',
    artist_refs: ['Florence Welch', 'Sia', 'Lady Gaga', 'Adele', 'Aurora'],
    parameters: {
      timbre: 'warm forward tone with widened upper bloom',
      texture: 'clean but pressured, smooth rather than grain-first',
      pressure: 'moderate-to-high pressure that increases into phrases',
      placement: 'forward and lifted, with front-loaded clarity',
      phrasing: 'sustained upward phrases with delayed emotional bloom',
      dynamics: 'starts contained, then expands in clear waves',
      articulation: 'clear but not percussive, open vowels on lift',
      registerBehavior: 'mix-led rise, avoids brittle squeeze, releases into widened top energy',
    },
    prompts: {
      studio: 'dramatic cinematic vocal, warm forward tone, pressured lift, swelling sustained phrasing, widescreen emotional rise',
      suno: 'dramatic cinematic vocal, warm forward tone, pressured mix-belt lift, swelling sustained phrases, widescreen emotional rise',
      udio: 'cinematic dramatic lead vocal, warm forward tone, blooming rise, sustained lift, pressured but controlled release',
    },
  },
  {
    id: 'fragile-forward',
    label: 'Fragile Forward',
    definition: 'Light, forward, intimate identity with controlled fragility and a preserved pitch core.',
    artist_refs: ['Billie Eilish', 'Troye Sivan', 'Phoebe Bridgers', 'Imogen Heap', 'Clairo'],
    parameters: {
      timbre: 'light and slightly bright with a soft core',
      texture: 'airy but controlled, never washed out',
      pressure: 'low pressure with carefully held support',
      placement: 'forward and close, intimate rather than distant',
      phrasing: 'held-back, human, slightly suspended',
      dynamics: 'small dynamic range with subtle swells',
      articulation: 'soft consonants with enough edge to preserve words',
      registerBehavior: 'stays close to chest-light mix transitions without obvious gear shifts',
    },
    prompts: {
      studio: 'light forward intimate vocal, controlled fragility, preserved pitch core, restrained lift, close detail',
      suno: 'light forward intimate vocal, controlled fragility, close-mic tone, restrained phrasing, preserved pitch core',
      udio: 'fragile forward lead, intimate and controlled, light tone, held-back phrasing, subtle tension',
    },
  },
  {
    id: 'raspy-edge',
    label: 'Raspy Edge',
    definition: 'Texture-first vocal identity with audible grain, friction, and emotional abrasion.',
    artist_refs: ['Miley Cyrus', 'Lewis Capaldi', 'P!nk', 'Janis Joplin', 'Chris Stapleton'],
    parameters: {
      timbre: 'forward midrange with worn warmth',
      texture: 'grainy, rough, friction-heavy',
      pressure: 'moderate push with deliberate abrasion',
      placement: 'forward and immediate',
      phrasing: 'direct and text-driven with hard emotional edges',
      dynamics: 'punchy emphasis rather than long bloom',
      articulation: 'clear consonants with bite',
      registerBehavior: 'leans on chest-dominant mix with crackle under pressure',
    },
    prompts: {
      studio: 'grainy forward vocal, emotional abrasion, rough edge, controlled push, expressive crackle',
      suno: 'grainy forward vocal, rough edge, emotional abrasion, controlled rasp, pressured expressive push',
      udio: 'raspy edge lead, grainy forward tone, expressive friction, worn warmth, controlled crack',
    },
  },
  {
    id: 'velvet-rnb-float',
    label: 'Velvet R&B Float',
    definition: 'Smooth suspended vocal glide with warmth, softness, and modern R&B polish.',
    artist_refs: ['SZA', 'Aaliyah', 'Summer Walker', 'Sade', 'Jhené Aiko'],
    parameters: {
      timbre: 'warm, rounded, gently glossy',
      texture: 'soft and smooth with slight breath cushion',
      pressure: 'low-to-moderate pressure with floating release',
      placement: 'centered and close',
      phrasing: 'elastic, fluid, lightly syncopated',
      dynamics: 'restrained and sensual',
      articulation: 'softened consonants with rhythmic control',
      registerBehavior: 'smooth chest-to-mix continuity',
    },
    prompts: {
      studio: 'smooth suspended vocal glide, warm soft tone, modern r&b polish, elastic phrasing, intimate control',
      suno: 'velvet r&b vocal, warm soft tone, suspended glide, intimate modern phrasing, polished and restrained',
      udio: 'smooth r&b lead, soft warmth, floating phrasing, close sensual delivery',
    },
  },
  {
    id: 'midrange-authority-pop',
    label: 'Midrange Authority Pop',
    definition: 'Commanding center-weight pop lead without excessive belt theatrics.',
    artist_refs: ['Dua Lipa', 'Sade', 'George Michael', 'Jessie Ware', 'Annie Lennox'],
    parameters: {
      timbre: 'centered, solid, polished midrange',
      texture: 'clean with minimal grain',
      pressure: 'moderate and controlled',
      placement: 'forward-center without nasal overpush',
      phrasing: 'tight and grounded',
      dynamics: 'stable with deliberate chorus lift',
      articulation: 'clear and rhythmic',
      registerBehavior: 'mix stays stable and chest-informed',
    },
    prompts: {
      studio: 'commanding center-weight pop lead, clean controlled midrange, rhythmic confidence, polished lift without belt theatrics',
      suno: 'midrange authority pop vocal, controlled power, clean tone, grounded phrasing, polished modern lead',
      udio: 'solid pop lead, center-weight authority, clean modern phrasing, restrained but confident lift',
    },
  },
]
